version: '3.8'
services:
  backend:
    build:
      context: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/api
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    command: yarn start:dev
    networks:
      - backend_network

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend_network
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: juan@teste.com
      PGADMIN_DEFAULT_PASSWORD: 123
    depends_on:
      - postgres
    networks:
      - backend_network
      
networks:
  backend_network:
    driver: bridge
  